# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b273a53352aa1addb9687a15f2d61b0a2131b2401a1a9e6fb486077120942920b6468419c6d1f9788e5f4f449a68768e16e6cdf9290b45a4e564a762ceb4ced6

test:
  secret_key_base: 029dd707057c00f746e4cf5dc03759816d7175841e2f356669d19fab8aeb3b97a57913129bfdf78ef1fb8a8ec155ab14ded4215f2d4a175330cbdcaecedf64b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
